### ISSUE TITLE
 'Baseline' object is not iterable

### ISSUE THREAD

**Issue by liuchanfeng165** [michuanhaohao/reid-strong-baseline#101]
hi , win doesnt support it as well , is it right?

Traceback (most recent call last):
  File "tools/test.py", line 68, in <module>
    main()
  File "tools/test.py", line 62, in main
    model.load_param(cfg.TEST.WEIGHT)
  File ".\modeling\baseline.py", line 176, in load_param
    for i in param_dict:
TypeError: 'Baseline' object is not iterable

**Comment by liuchanfeng165** [comment]
been sovled~

**Comment by fengjiufa** [comment]
can you tell me how to solve this question?

**Comment by eddielyc** [comment]
@fengjiufa  it seems that the checkpoint saved the whole model instead of model's state dict
replace the param_dict = torch.load(trained_path) as   param_dict = torch.load(trained_path).state_dict()

**Comment by fengjiufa** [comment]
Ok！Thank you！I'll try to do as you said.------------------ 原始邮件 ------------------
发件人: "Yichen Lu"<notifications@github.com>
发送时间: 2019年11月21日(星期四) 上午10:09
收件人: "michuanhaohao/reid-strong-baseline"<reid-strong-baseline@noreply.github.com>;
抄送: "jiufafeng"<1124008433@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [michuanhaohao/reid-strong-baseline]  'Baseline' object is notiterable (#101)



@fengjiufa  it seems that the checkpoint saved the whole model instead of model's state dict
 replace the param_dict = torch.load(trained_path) as   param_dict = torch.load(trained_path).state_dict()
 
&mdash;
