### ISSUE TITLE
Error loading parameters from checkpoint

### ISSUE THREAD

**Issue by Rusteam** [michuanhaohao/reid-strong-baseline#12]
Hi there,
Thanks for the awesome job.

I trained a model using mtmc data, but when I try to initialize a model using modelling.baseline.Baseline it throws the error that names of parameters don't match.

![image](https://user-images.githubusercontent.com/22130831/54943690-dd417080-4f42-11e9-81bb-c22c8b5c015f.png)
![image](https://user-images.githubusercontent.com/22130831/54943719-f4805e00-4f42-11e9-9268-59bbaeb64a7f.png)

However, when I remove all 'base.' prefixes it still throws the same error on 'bottleneck.weights' parameters. I couldn't find the way to solve this one.
![image](https://user-images.githubusercontent.com/22130831/54943829-31e4eb80-4f43-11e9-965d-70d6d215850d.png)

**Comment by shaoniangu** [comment]
Hi, thank you for the reminder. The function load_param() in backbone is used for initializing backbone's parameters from ImageNet pretrained model, and the function load_param() in baseline is used for initializing the whole model from self trained model when testing. If you want to continue your training process based on your trained model, you need to load not only the model parameters but also the optimizer parameters. And the error you meet is caused by the mismatch mistake between self trained model and the backbone model structure. We have updated this function just now. We will further check this function by detailed testing. Please issue us if you meet new problems.
Thank you again for your kind reminder.

**Comment by Rusteam** [comment]
The problem is that names of parameters don't match when building a model for testing.
The issue still persists

**Comment by Rusteam** [comment]
oops, overlooked this one: "`PRETRAIN_CHOICE` from 'imagenet' to 'self'".
Loaded now.
My bad.

**Comment by shaoniangu** [comment]
OK. Thank you again for your reminder.
