### ISSUE TITLE
question about center loss weight

### ISSUE THREAD

**Issue by zhukuan96** [michuanhaohao/reid-strong-baseline#43]
if we multiply 1./0.0005. Is the center_loss_weight still work?
 
![de473ab207fa020b8ca026bbe7bbd73](https://user-images.githubusercontent.com/47589249/59330496-393aba80-8d24-11e9-9760-e22a09adfaa6.png)

**Comment by shaoniangu** [comment]
It is a tricky operation of center loss optimization using SGD. There are two optimizers in model training with center loss. One is for optimizing model parameters, the other one is for optimizing feature centers. When optimizing model parameters, because the center loss is so large at the early epoches that the center_loss_weight matters to decrease the grad of center loss. And when optimizing feature centers by using SGD, the center_loss_weight should be removed. We also did several experiments on the value of center_loss_weight and the choice of whether to  multiply 1./center_loss_weight when optimizing feature centers. We find out that this operation does matters.

**Comment by goodluckcwl** [comment]
Thanks!
